service: mlb-scraper
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt
    invalidateCaches: true
    usePipenv: true
  secrets: ${file(keys.yml):${self:custom.stage}}

provider:
  name: aws
  versionFunctions: True
  runtime: python2.7
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'production'}
  stackName: api-operations-${self:provider.stage}
  profile: ${opt:aws-profile, 'default'}
  tags:
    VERSION: "${env:REVISION}"
  deploymentBucket:
    name: mlb-scraper

functions:
  - ${file(services/resources/getLineMovement/setup.yml)}
  - ${file(services/resources/getPublic/setup.yml)}

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation

package:
  individually: true
  exclude:
    - .idea/**
    - .git/**
    - services/**
    - scripts/**
    - tests/**
    - venv/**
    - .gitattributes
    - node_modules/**
    - .gitignore
    - .pyenv/**
